apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: exam
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: exam
spec:
  selector:
    app: backend
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: exam
spec:
  selector:
    app: database
  ports:
  - port: 5432
    targetPort: 5432
  clusterIP: None